package de.melays.smash.errors;

public enum MError {
	OKAY, UNKNOWN, LOBBY_LOC_MISSING, ITEM_LOC_MISSING, GAME_LOC_MISSING, SPEC_LOC_MISSING, BACK_LOC_MISSING,CORNER_1_MISSING,CORNER_2_MISSING,
	ARENA_ALLREADY_LOADED, ARENA_UNKNOWN, ARENA_LOADING,
	ARENA_FULL, OKAY_AS_SPEC, ALREADY_INGAME
}
